const menuItems = [
  // Minuman
  { id: 1, name: "Kopi Hitam", price: 4000, category: "minuman", popular: true },
  { id: 2, name: "Kopi ABC Susu", price: 4000, category: "minuman", popular: true },
  { id: 3, name: "Kopi ABC Klepon", price: 6000, category: "minuman", popular: true },
  { id: 4, name: "Kopi Goodday Freeze", price: 6000, category: "minuman" },
  { id: 5, name: "Kopi Goodday Cappucino", price: 6000, category: "minuman", popular: true },
  { id: 6, name: "Kopi Goodday", price: 5000, category: "minuman" },
  { id: 7, name: "Kopi Putih", price: 5000, category: "minuman" },
  { id: 8, name: "Chocolatos Matcha", price: 6000, category: "minuman" },
  { id: 9, name: "Chocolatos", price: 6000, category: "minuman" },
  { id: 10, name: "Milo", price: 6000, category: "minuman" },
  { id: 11, name: "Teh Manis", price: 5000, category: "minuman" },
  { id: 12, name: "Teh Tawar", price: 2000, category: "minuman" },
  { id: 13, name: "Teh Tarik", price: 6000, category: "minuman" },
  { id: 14, name: "Nutrisari Jeruk Peras", price: 5000, category: "minuman" },
  { id: 15, name: "Nutrisari Sweet Orange", price: 5000, category: "minuman" },
  { id: 16, name: "Nutrisari Anggur", price: 5000, category: "minuman" },
  { id: 17, name: "Nutrisari Blewah", price: 5000, category: "minuman" },
  { id: 18, name: "Nutrisari Strawberry", price: 5000, category: "minuman" },
  { id: 19, name: "Teajus Apel", price: 4000, category: "minuman" },
  { id: 20, name: "Teajus Gulbat", price: 4000, category: "minuman" },
  { id: 21, name: "Teajus Lemon", price: 4000, category: "minuman" },
  { id: 22, name: "Teajus Madu", price: 4000, category: "minuman" },
  { id: 36, name: "Drink Bengbeng", price: 6000, category: "minuman" },
  { id: 37, name: "Susu Dingin", price: 5000, category: "minuman" },
  { id: 38, name: "Susu Panas", price: 5000, category: "minuman" },
  { id: 39, name: "Susu Jahe", price: 5000, category: "minuman" },

  // Makanan
  { id: 23, name: "Indomie Goreng", price: 8000, category: "makanan", popular: true },
  { id: 24, name: "Indomie Kuah", price: 8000, category: "makanan", popular: true },
  { id: 25, name: "Indomie Goreng + Telur", price: 12000, category: "makanan" },
  { id: 26, name: "Indomie Kuah + Telur", price: 12000, category: "makanan" },
  { id: 27, name: "Indomie Double", price: 15000, category: "makanan" },
  { id: 28, name: "Indomie Double + Telur", price: 19000, category: "makanan", popular: true },
  { id: 29, name: "Otak-otak Gowreng", price: 10000, category: "makanan" },
  { id: 30, name: "Kentang Gowreng", price: 13000, category: "makanan" },
  { id: 31, name: "Sosis Gowreng", price: 10000, category: "makanan" },
  { id: 32, name: "Mix Gowreng", price: 20000, category: "makanan" },
  { id: 33, name: "Nasi", price: 5000, category: "makanan" },
  { id: 34, name: "Nasi Telur", price: 15000, category: "makanan" },
  { id: 35, name: "Nasi Ayam Geprek", price: 15000, category: "makanan" },
];
